### ISSUE TITLE
mention of 900913 in example.map throws warning on logs

### ISSUE THREAD

**Issue by pvgenuchten** [PDOK/mapserver-docker#25]
for the example mapfile provided the logs show this error:

2022-02-09 11:47:43: (mod_fastcgi.c.421) FastCGI-stderr: msProcessProjection(): Projection library error. proj error "no arguments in initialization list" for "init=epsg:900913"

probably related to mention of 900913 in https://github.com/PDOK/mapserver-docker/blob/3c9d69a4c6fc9bda3d4c0fff9ba27bf92807ac50/example/example.map#L41

suggest to add the projection to poj, because it is generally used, however it would be better to use epsg:3857

**Comment by WouterVisscher** [comment]
Hi @pvgenuchten 
We discussed your suggestion internally, we plan to removed the EPSG:900913 from the "ows_srs" in the example 😄 
But how to add additional proj (like in your pull request) is a valid point. 
For now we will added the necessary steps needed for adding addtional proj in the documentation.

**Comment by WouterVisscher** [comment]
@pvgenuchten I've updated the documentation in pull request https://github.com/PDOK/mapserver-docker/pull/27
If you have additions please let us know
