### ISSUE TITLE
Restricted use of port 80

### ISSUE THREAD

**Issue by sgagnonNRCan** [PDOK/mapserver-docker#29]
Some organization are restricting the use of port 80.

Is there a way to configure a different port to use on localhost?

thanks.

**Comment by WouterVisscher** [comment]
Hi @Sigagnon, sorry for the late reaction
Yes, regarding 'deployment' (running het docker container) you should be able to use a different port by changing the `-p`  parameter like

```
docker run -e MS_MAPFILE=/srv/data/example.map --rm -d \
            -p 8080:80 --name mapserver-example -v `pwd`/example:/srv/data pdok/mapserver
```

so the service is running on port 8080. 

Or are you refering to the `EXPOSE 80` in the Dockerfile? 
You could probably tackle that issue by using a multistage Dockerfile and a custom lighttpd config.

**Comment by Sigagnon** [comment]
Thanks @WouterVisscher,

Works fine after por.t mapping. The issue  was somewhere else not in your docker image.
