### ISSUE TITLE
Mapserver 8

### ISSUE THREAD

**Issue by edalevol** [PDOK/mapserver-docker#56]
Hello. Are there any plans of updating the image to use mapserver 8?

**Comment by roelarents** [comment]
Good question. Yes. We're having some (blocking) issues though, i.e. https://github.com/MapServer/MapServer/issues/6973 and https://github.com/MapServer/MapServer/issues/6966. But another try on fixing those is on our backlog.

**Comment by edalevol** [comment]
Ok, thanks for the quick reply. I guess I will keep an eye open :)
