### ISSUE TITLE
403 error on / -- can easily be solved

### ISSUE THREAD

**Issue by dhrp** [PDOK/mapserver-docker#58]
### Symptom:
When starting the service with docker the / gives a 403 error. By itself this is confusing, but not necessarily a problem. 

### Root cause
lighthttpd already can serve it's index.html, if you request it `GET /index.html`, but doesn't have the mimetype connected. `Make sure that mimetype.assign is configured with the file extensions you are serving.` 

It becomes more problematic when used in combination with a helm chart like: https://github.com/Signalen/helm-charts/tree/master/charts/mapserver (which is otherwise good), the service doesn't start because / doesn't return a 2xx response. and doesn't pass the health check.

### Idea
Fix the mimetype.assign, and replace the default index.html with something a little more friendly; even if it is a few links to example queries.

### Note 
That there is a 403 error on index.html has been reported before in https://github.com/PDOK/mapserver-docker/issues/42, but I created this as a new issue because I think it can be easily fixed.

**Comment by kad-dirc** [comment]
Hi @dhrp ,

For healthchecks we advice to perform a simple GetCapabilities request, e.g. `http://127.0.0.1:80/mapserver?REQUEST=GetCapabilities&SERVICE=WMS`
When you check on "/", you only check if lighttp is healthy. But you want to know if the combination of lighttp, mapserver and your data is healthy.

When do you get the message about "mimetype.assign"?
I have added a line to the lighttp config file to ensure "/" is mapped to "index.html", but I need to double check if I don't break things

**Comment by IceflowRE** [comment]
On large server with thousands of layer, querying the capabilities i cannot advise this.
